Description: Minecraft cloudformation
# To Do
# Snapshots
# Snapshot lifecycle policy
# CloudWatch ALarm and SNS Topic

Parameters:
    InstanceType:
        Description: Minecraft server instance type
        Type: String
        Default: t3.small
    SshKey:
        Description: The SSH key for administrative access to the EC2 instance.
        Type: String
        Default: mineformationKP
    ExistingDomainName:
        Description: Optional, if you'd like to use Route 53 to regiser a CNAME.
        Type: String
    AMI:
        Description: Should be a unix based AMI. Tested on only the default.
        Type: String
        Default: ami-0b33d91d
    Region:
        Description: Starting to build this out.
        Type: String
        Default: us-east-1
    DownloadLink:
        Description: Link to the version of Minecraft Server you want.
        Type: String
        Default: https://launcher.mojang.com/v1/objects/fe123682e9cb30031eae351764f653500b7396c9/server.jar
    EmailEndpoint:
        Description: The email addess you'd like to use to receive event information
        Type: String
        Default: therealbenforce@gmail.com
Conditions:
    RegisterRoute53:
        !Not [!Equals [!Ref ExistingDomainName, '']]
Resources:
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: All that is necessary for Minecraft and administration
            SecurityGroupIngress:
                -
                    IpProtocol: tcp
                    FromPort: 22
                    ToPort: 22
                    CidrIp: 0.0.0.0/0
                -
                    IpProtocol: tcp
                    FromPort: 25565
                    ToPort: 25565
                    CidrIp: 0.0.0.0/0

    myEIP:
        Type: "AWS::EC2::EIP"
        Properties:
            InstanceId: !Ref myEC2

    myEC2:
        Type: "AWS::EC2::Instance"
        Properties:
            EbsOptimized: false
            ImageId: !Ref AMI
            InstanceInitiatedShutdownBehavior: stop
            InstanceType: !Ref InstanceType
            KeyName: !Ref SshKey
            SecurityGroups:
                - !Ref InstanceSecurityGroup
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    yum update -y
                    mkdir minecraft
                    cd minecraft
                    wget -O minecraft_server.jar ${DownloadLink}
                    java -jar minecraft_server.jar nogui
                    sed -i -- 's/false/true/g' eula.txt
                    java -jar minecraft_server.jar nogui

    DNSRecord:
        Type: AWS::Route53::RecordSet
        Condition: RegisterRoute53
        Properties:
            HostedZoneName: !Join ['', [!Ref ExistingDomainName, .]]
            Comment: DNS name for MINEformation.
            Name: !Join ['', [!Ref 'AWS::StackName', ., !Ref 'ExistingDomainName']]
            Type: A
            TTL: 300
            ResourceRecords:
                - !Ref myEIP

##############
# MONITORING #
##############
    mineSNS:
        Type: "AWS::SNS::Topic"
        Properties:
          Subscription:
            - Endpoint: !Ref EmailEndpoint
              Protocol: email
          TopicName: MineSnsTopic

    ShutdownTestAlarm:
    # Need to prepare minecraft boot script before scheduling ec2:recover alarm action
        Type: AWS::CloudWatch::Alarm
        Properties:
          AlarmDescription: Trigger a notification when instance status check fails for 15 consecutive minutes.
          Namespace: AWS/EC2
          MetricName: StatusCheckFailed_System
          Statistic: Minimum
          Period: '60'
          EvaluationPeriods: '15'
          ComparisonOperator: GreaterThanThreshold
          Threshold: '0'
          AlarmActions:
            - !Ref mineSNS
          Dimensions:
          - Name: InstanceId
            Value:
              Ref: myEC2
