Description: Minecraft cloudformation
Parameters:
    HostedZoneId: 
        Description: Your HostedZoneID
        Type: String
        Default: Z1ZGYX2ZIYACUH
    Domain:
        Description: Your domain name.
        Type: String
        Default: therealbenforce.com
Resources:
    DNSRecord:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: !Ref HostedZoneId
            Comment: DNS name for MINEformation.
            Name: !Join ['', ['mineformation', ., !Ref 'Domain']]
            Type: A
            TTL: 900
            ResourceRecords: 
                - 192.168.10.10